make: main.c rush02.c print.c file.c aux.c dict.c check.c
	cc -Wall -Wextra -Werror main.c rush02.c print.c file.c aux.c dict.c check.c -o rush-02
fclean: rush-02
	rm rush-02
test:
	cc -Wall -Wextra main.c rush02.c print.c file.c aux.c dict.c check.c -o rush-02
