SRC =main.c rush02.c print.c file.c aux.c dict.c check.c transcript.c aux2.c

make: ${SRC}
	cc -Wall -Wextra -Werror ${SRC} -o rush-02
fclean: rush-02
	rm rush-02
test:
	cc -Wall -Wextra ${SRC} -o rush-02
